### ISSUE TITLE
SQL number default dialect (low priority)

### ISSUE THREAD

**Issue by BCsabaEngine** [nwoltman/node-mysql-plus#5]
It is similar to earlier default timestamp dialect, the number type default values are incorrect.
db.ColTypes.int(11).notNull().default(5) reported as "'5'" and modified to "5".

The following modifications solve the problem (ColumnDefinition.js):
1. Remove **if (typeof value === 'number') { return "'" + value + "'"; }** correction.
2. Use permissive compare at **if (this._default === columnDefinition._default)**, use only two equalsign: **if (this._default == columnDefinition._default)**
So default values will be "more equals" without " or '.

**Comment by nwoltman** [comment]
If MariaDB reports a column's default value as a string, it would be better to also use a string in the column definition. Does doing this solve the problem?

```js
db.ColTypes.int(11).notNull().default('5')
```

**Comment by BCsabaEngine** [comment]
Every try ( ' or " or ` ) makes the same result. (Image created by some console.log in TableDefinition.js with console.log(oldColumnDefinition) + console.log(newColumnDefinition))

![mysqlplus-def](https://user-images.githubusercontent.com/20396372/87851420-db9a7980-c8f8-11ea-8c72-6c3c1458955c.jpg)

**Comment by nwoltman** [comment]
Oh, I see now, I had it backwards. MariaDB reports the default as a number and MySQL reports it as a string, which is why I added the `if (typeof value === 'number')` part to the `escapeDefault()` function.

Regardless, I ran the test suite against MariaDB and a lot of tests failed. It turns out there are many differences between MariaDB and MySQL. There are enough differences that I don't think it makes sense to try to support both databases in this package (without a major effort to rearchitect the code to support both databases, which I don't really have time for). For this reason, I'd suggest that you fork this repo and create a separate package that's specifically for MariaDB.
